# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LsWh0Gy4gWI0D2NLByLKlP3ldTmLH3u
"""

import matplotlib.pyplot as plt

def linear_search(arr, x):
    for i in range(len(arr)):
        if arr[i] == x: # Indented this line by 4 spaces
            return i  # Indented this line by 4 spaces
    return -1

arr = [2, 3, 4, 10, 40]
x = 50
# Function call
result = linear_search(arr, x)
if result == -1:
    print("Element is not present in array")
else:
    print("Element is present at index", result)

n = [10, 20, 50, 456, 600, 900, 1000]
time = [0.0002, 0.0003, 0.0008, 0.0015, 0.0030, 0.0075, 0.0150]
plt.plot(n, time)
plt.xlabel('Number of Elements')
plt.ylabel('Time Taken')
plt.title('Time Complexity of Linear Search')
plt.show()
