# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yP2eAjhafL57Cnm1IIsES3ZNAoWo44cC
"""

import matplotlib.pyplot as plt


def insertionSort(arr):

    for i in range(1, len(arr)):
        key = arr[i]

        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key


arr = []
n = int(input("Enter number of elements: "))
for i in range(n):
    element = int(input(f"Enter element {i+1}: "))
    arr.append(element)


insertionSort(arr)


print("Sorted array is:", arr)


x = [2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [10, 0.1, 0.3, 0.5, 0.7, 1.0, 1.3, 1.5, 2.0]
plt.plot(x, y)
plt.xlabel('Size of array')
plt.ylabel('Complexity')
plt.title('Time Complexity of Insertion Sort')
plt.show()